<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moryx.Orders" />
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyApplication\MyApplication.csproj" />
  </ItemGroup>

</Project>